#!/bin/sh

# Somehow nuxt generate ignores environment variables other than those inside .env.production.
# This scripts works around the issue by writing the necessary variables into .env.production before
# invoking the command.

ENV_FILE="$(dirname $(dirname $(realpath $0)))/.env.production"

truncate -s 0 $ENV_FILE

echo "NODE_ENV=\"${NODE_ENV}\"" >> $ENV_FILE
echo "INFURA_PROJECT_ID=\"${INFURA_PROJECT_ID}\"" >> $ENV_FILE
echo "ETHERSCAN_KEY=\"${ETHERSCAN_KEY}\"" >> $ENV_FILE
echo "BSCSCAN_KEY=\"${BSCSCAN_KEY}\"" >> $ENV_FILE
echo "ALCHEMY_KEY=\"${ALCHEMY_KEY}\"" >> $ENV_FILE
echo "ETH_GAS_STATION_KEY=\"${ETH_GAS_STATION_KEY}\"" >> $ENV_FILE
echo "DEFI_PULSE_STATION_KEY=\"${DEFI_PULSE_STATION_KEY}\"" >> $ENV_FILE
echo "GRAPH_BUILDR_SWAP_ETHEREUM_MAINNET=\"${GRAPH_BUILDR_SWAP_ETHEREUM_MAINNET}\"" >> $ENV_FILE
echo "GRAPH_BUILDR_ETHEREUM_ROPSTEN=\"${GRAPH_BUILDR_ETHEREUM_ROPSTEN}\"" >> $ENV_FILE
echo "GRAPH_BUILDR_SWAP_ETHDEV=\"${GRAPH_BUILDR_SWAP_ETHDEV}\"" >> $ENV_FILE
echo "GRAPH_BUILDR_SWAP_ETHEREUM_ROPSTEN=\"${GRAPH_BUILDR_SWAP_ETHEREUM_ROPSTEN}\"" >> $ENV_FILE
echo "GRAPH_BUILDR_BINANCE_TESTNET=\"${GRAPH_BUILDR_BINANCE_TESTNET}\"" >> $ENV_FILE
echo "GRAPH_BUILDR_BSCDEV=\"${GRAPH_BUILDR_BSCDEV}\"" >> $ENV_FILE
echo "GRAPH_BUILDR_ETHDEV=\"${GRAPH_BUILDR_ETHDEV}\"" >> $ENV_FILE
echo "GRAPH_BAND_BINANCE_TESTNET=\"${GRAPH_BAND_BINANCE_TESTNET}\"" >> $ENV_FILE
echo "GRAPH_BAND_BSCDEV=\"${GRAPH_BAND_BSCDEV}\"" >> $ENV_FILE
echo "GRAPH_BAND_BINANCE_MAINNET=\"${GRAPH_BAND_BINANCE_MAINNET}\"" >> $ENV_FILE
echo "GRAPH_BUILDR_BINANCE_MAINNET=\"${GRAPH_BUILDR_BINANCE_MAINNET}\"" >> $ENV_FILE
echo "GRAPH_BUILDR_ETHEREUM_MAINNET=\"${GRAPH_BUILDR_ETHEREUM_MAINNET}\"" >> $ENV_FILE
echo "TOKEN_BRIDGE_MAINNET=\"${TOKEN_BRIDGE_MAINNET}\"" >> $ENV_FILE
echo "TOKEN_BRIDGE_TESTNET=\"${TOKEN_BRIDGE_TESTNET}\"" >> $ENV_FILE
echo "BACKEND_API=\"${BACKEND_API}\"" >> $ENV_FILE
echo "ENABLE_MAINTENANCE=\"${ENABLE_MAINTENANCE}\"" >> $ENV_FILE
